- src/controller/request/invoice-request.ts
- src/controller/response/transaction-report-response.ts
- src/controller/user-controller.ts
- src/service/invoice-service.ts
- src/service/transaction-service.ts
- test/unit/controller/user-controller.ts
- test/unit/service/invoice-service.ts
- Bug where credit invoice entries contained products from SubTransactions with different sellers
- Bug where transaction report reported products being sold from subTransactions from different sellers.
> Fixed Transaction Mapping and Sellers bugs

- src/controller/request/invoice-request.ts
- src/controller/response/transaction-report-response.ts
- src/controller/user-controller.ts
- src/service/invoice-service.ts
- src/service/transaction-service.ts
- test/unit/service/invoice-service.ts
Fixed two bugs:  
- Bug where credit invoice entries contained products from SubTransactions with different sellers  
- Bug where transaction report reported products being sold from subTransactions from different sellers.
> Fixed Transaction Mapping and Sellers bugs 

- src/service/user-service.ts
Somehow the collations were not correct, so we fixed them.
> Fixed incorrect collation

- src/entity/transactions/transaction.ts
- src/service/user-service.ts
Improved performance and deleted some collations that were messing up the user search.
> Everything works now

- src/controller/debtor-controller.ts
Roy's code was bad and he should feel bad.
> Changed route to the correct one for delete single fine

- src/controller/debtor-controller.ts
- src/controller/request/debtor-request.ts
- src/controller/response/balance-response.ts
- src/controller/response/debtor-response.ts
- src/controller/user-controller.ts
- src/database/database.ts
- src/entity/transactions/transaction.ts
- src/entity/transactions/transfer.ts
- src/helpers/pagination.ts
- src/helpers/validators.ts
- src/service/balance-service.ts
- src/service/debtor-service.ts
- src/subscriber/index.ts
- src/subscriber/transaction-subscriber.ts
- src/subscriber/transfer-subscriber.ts
- test/seed.ts
- test/unit/controller/debtor-controller.ts
- test/unit/controller/user-controller.ts
- test/unit/service/balance-service.ts
- test/unit/service/debtor-service.ts
- test/unit/subscribe/transaction-subscriber.ts
- test/unit/subscribe/transfer-subscriber.ts
Fixes https://github.com/GEWIS/sudosos-backend/issues/67.
@JustSamuel Can you also check whether the Swagger spec is consistent with the actual implementation? It should be the case, but a double check never hurts.
> Fine design improvements

- src/controller/invoice-controller.ts
Fixes https://github.com/GEWIS/sudosos-backend/issues/76.
> Add invoice pagination to swagger spec

- src/controller/event-controller.ts
- src/controller/event-shift-controller.ts
Fixes https://github.com/GEWIS/sudosos-backend/issues/96.
> Fix OpenAPI docs for some event-related endpoints

- .github/workflows/update-client.yml
Created an app to get a token for updating the sudosos-client repo.
> Automagic updating of sudosos-client via dispatches.

- src/controller/authentication-controller.ts
- src/controller/authentication-secure-controller.ts
- src/controller/banner-controller.ts
- src/controller/debtor-controller.ts
- src/controller/event-controller.ts
- src/controller/event-shift-controller.ts
- src/controller/response/transaction-response.ts
- src/controller/root-controller.ts
- src/controller/simple-file-controller.ts
- src/controller/test-controller.ts
- src/controller/transaction-controller.ts
- src/controller/user-controller.ts
- test/unit/controller/banner-controller.ts
- test/unit/controller/transaction-controller.ts
- test/unit/controller/user-controller.ts
- test/unit/helpers/validators.ts
> Fixes HTTP status codes for DELETE and empty bodies

- src/service/stripe-service.ts
- test/unit/service/stripe-service.ts
> Wrap Stripe updates in a database transactions

- src/controller/authentication-controller.ts
- src/controller/authentication-secure-controller.ts
- src/controller/banner-controller.ts
- src/controller/debtor-controller.ts
- src/controller/event-controller.ts
- src/controller/event-shift-controller.ts
- src/controller/response/transaction-response.ts
- src/controller/root-controller.ts
- src/controller/simple-file-controller.ts
- src/controller/test-controller.ts
- src/controller/transaction-controller.ts
- src/controller/user-controller.ts
- src/service/stripe-service.ts
- src/subscriber/transfer-subscriber.ts
- test/unit/controller/banner-controller.ts
- test/unit/controller/transaction-controller.ts
- test/unit/controller/user-controller.ts
- test/unit/helpers/validators.ts
- test/unit/service/stripe-service.ts
- **Fixes HTTP status codes for DELETE and empty bodies (#129)**
- Corrected HTTP return codes for DELETE requests and empty bodies (Issue #21).
- **Ensure that only LOCAL_USERS can get a reset password token (#127)**
- Implemented restrictions to allow only LOCAL_USERS to retrieve reset password tokens.
- **Wraps stripe updates in a transaction (#130)**
- Encapsulated stripe updates within a transaction for improved integrity.
- **Hotfix for stripe transaction erroring on deposit update (#131)**
- Resolved a bug causing typeorm to error when saving deposit status within a transaction.
- **Hotfix stripe transaction bug (#132)**
- Addressed a bug where typeorm would error when trying to save deposit status within a transaction.
> Merge Develop into Main

- src/controller/stripe-controller.ts
- src/service/stripe-service.ts
- test/unit/service/stripe-service.ts
> Enforces a minimum top-up for stripe deposits.

- src/controller/stripe-controller.ts
- src/cron.ts
- src/index.ts
- src/service/stripe-service.ts
- test/unit/service/stripe-service.ts
The following features are included:
Enforces a minimum top-up for stripe deposits. [(135)](https://github.com/GEWIS/sudosos-backend/commit/3f57b0b42201c81d508e929797faa69c770442ad)
Fixed bug where bindings were not overwritten for the cron tasks. [(145)](https://github.com/GEWIS/sudosos-backend/commit/0aa1fd55e333fa9edb958f15215d310baf390ac9)
> Merge features from develop to main

- src/gewis/gewis.ts
> feat: allow local users to update email

- src/controller/request/user-request.ts
- src/controller/request/validators/update-local-request-spec.ts
- src/gewis/gewis.ts
- test/unit/controller/user-controller.ts
> feat: toggle extensive data processing

- src/service/debtor-service.ts
- test/unit/service/debtor-service.ts
Fixes https://github.com/GEWIS/sudosos-backend/issues/137, verified with a new test case.
> fix: user still having a fine after deleting fine with positive balance

- .github/workflows/release.yml
- .releaserc.json
Based on our experiences from `sudosos-frontend` we now also have semantic release on the backend.
> ci: added semantic release

- src/controller/balance-controller.ts
- src/service/balance-service.ts
- test/unit/controller/balance-controller.ts
- test/unit/service/balance-service.ts
Adds query param for if deleted users should be returned by the balance query
#167 
> Fix: balance deleted users

- README.md
Same design as sudosos-frontend
- Documentation improvement
> docs: badges and pimp readme

- src/controller/debtor-controller.ts
- src/controller/response/debtor-response.ts
- src/service/debtor-service.ts
- test/unit/controller/debtor-controller.ts
- test/unit/service/debtor-service.ts
Route for getting an overview of all the handed out and waived fines. Next step will be allowing it to be reported as a pdf.
#155 (does not close)
> Feature: fine reporting

- .github/workflows/build.yml
As discussed in the group chat, this should possibly fix the base reporting of the coverage.
#32
> ci: attempt to fix coverage base reporting

- .github/workflows/docker-build.yml
- .github/workflows/docker-push.yml
- .github/workflows/release.yml
Since we have been rate limited we will just remove QEMU.
> ci: removed qemu setup

- test/unit/service/debtor-service.ts
The test case `should correctly put two fines in same userFineGroup` sometimes fails, because the internal state has changed in the previous test case. The additions are now properly cleaned up.
> fix: debtor test case inconsistent test results

- src/gewis/service/gewisdb-service.ts
- src/service/user-service.ts
> fix: add param for deleting accounts if they have no balance

- src/database/seed.ts
Migration table is missing when running `npm run seed`, which makes it difficult to test migrations.
> fix: migration table missing when seeding database

- src/controller/user-controller.ts
- src/helpers/timestamps.ts
- src/service/transaction-service.ts
- src/service/transfer-service.ts
- src/service/user-service.ts
- test/seed.ts
- test/unit/controller/user-controller.ts
- test/unit/service/transfer-service.ts
Time filters for financial mutations.
Implements https://github.com/GEWIS/sudosos-backend/issues/213
> feat: financial mutations filters

- package.json
The eslint CI job always passed because it did not check anything. Now it does! Bring back the Grolsch Kruidige Tripel!
> ci: fix eslint command

- src/controller/response/invoice-response.ts
- src/service/invoice-service.ts
> fix: added missing reference to invoice response

- package-lock.json
- package.json
- src/controller/invoice-controller.ts
- src/controller/request/invoice-request.ts
- src/controller/request/validators/invoice-request-spec.ts
- src/controller/response/invoice-response.ts
- src/database/database.ts
- src/entity/invoices/invoice-status.ts
- src/entity/invoices/invoice.ts
- src/migrations/1722118077157-invoice-rework.ts
- src/service/invoice-pdf-service.ts
- src/service/invoice-service.ts
- src/service/transfer-service.ts
- src/subscriber/invoice-status-subscriber.ts
- test/seed.ts
- test/unit/controller/invoice-controller.ts
- test/unit/service/invoice-pdf-service.ts
- test/unit/service/invoice-service.ts
Preface: I accidentally grew the scope of this PR.
This PR adds 2 extra columns to the `Invoice` entity. Namely `date` for, well, date, and `attention` for the extra attention row used when addressing companies. 
This PR also adds a `latestStatus` which is the latest status update of the Invoice. This is needed to do effective database queries on Invoice state, which I found to be a must when creating the frontend. I kept the endpoints the same, such that it integrates nicely.
TODO:
#77 
> feat: invoice entity rework

- src/migrations/1722118077157-invoice-rework.ts
`default: ''` caused mariadb errors.
> fix: MariaDB specific dialect mistake

- src/migrations/1722004753128-write-offs.ts
- src/migrations/1722118077157-invoice-rework.ts
> Fix: mariadb migration invoice

- src/rbac/default-roles.ts
Users are currently not allowed to retrieve their own roles with permissions
> fix(RBAC): Allow all users to get their own roles

- src/controller/payout-request-controller.ts
- src/controller/response/simple-file-response.ts
Mismatch in swagger and implementation
> fix: pdf return type

- src/service/payout-request-service.ts
> refactor: Update order criteria for PayoutRequest entity

- src/service/invoice-service.ts
Title self explanatory. Probably leftover from https://github.com/GEWIS/sudosos-backend/pull/250.
> fix: leftover console.error dumping thousands of lines in test log

- src/controller/response/stripe-response.ts
- src/controller/stripe-webhook-controller.ts
- src/database/database.ts
- src/entity/stripe/stripe-deposit.ts
- src/entity/stripe/stripe-payment-intent-status.ts
- src/entity/stripe/stripe-payment-intent.ts
- src/entity/transactions/transfer.ts
- src/migrations/1722869409448-stripe-payment-intents.ts
- src/service/stripe-service.ts
- src/service/transfer-service.ts
- test/seed.ts
- test/unit/controller/stripe-controller.ts
- test/unit/controller/stripe-webhook-controller.ts
- test/unit/controller/user-controller.ts
- test/unit/database.ts
- test/unit/service/stripe-service.ts
Standalone of https://github.com/GEWIS/sudosos-backend/pull/254.
Prework for https://github.com/GEWIS/sudosos-backend/issues/197.
> feat(stripe): separate Stripe payment intents from StripeDeposit entity

- src/helpers/query-filter.ts
Victor found this issue when trying the new `GET /pointofsale/:id/associates` endpoint. It returned an HTTP 500.
I hate SQL dialects :(
> fix: MariaDB error when having WHERE IN empty list

- src/migrations/1722517212441-nested-product-categories.ts
Fixes two mistakes/errors in the nested product categories migration:
1. Even though a [closure table](https://orkhan.gitbook.io/typeorm/docs/tree-entities#closure-table) is used to create the tree structure for product categories, TypeORM still creates a `parentId` column in the `product_category` table. After some thinking, this makes sense: how else would you distinguish your parents from your ancestors? Stupid me was stupid.
2. For every record in the `product_category` table, the closure table should include a mapping from each record to itself. The migration did not do this (but now it does)!
These two things therefore will need manual fixing in the test environment, as there already is a newer migration in the list. However, we can also undo the Stripe migration and then redo this …
> fix: migration mistakes regarding nested product categories

- Dockerfile
- init_scripts/start.sh
Fixes https://github.com/GEWIS/sudosos-backend/issues/268 and (hopefully) also https://github.com/GEWIS/sudosos-backend/issues/265.
> fix: Docker production issues with static files and logs

- src/controller/stripe-webhook-controller.ts
- src/service/stripe-service.ts
- test/unit/controller/stripe-webhook-controller.ts
Critical issue where Stripe events are no longer being handled correctly on production. This PR adds more validation and logging to the webhook related endpoints, so we can get a better understanding what is going on.
> fix: add extra validation and logging to Stripe webhooks

- package.json
- src/controller/seller-payout-controller.ts
- test/unit/controller/seller-payout-controller.ts
Test suite seems to hang in the CI, this branch / PR is to test and find out what causes it.
Caused in PR #279 
> Fix hanging test suite

- src/cron.ts
- src/index.ts
Some tasks are executed by each worker, but that is a bit unnecessary and even causes problems when each worker tries to lock the same database table.
> feat: move all initialization functions and timed events to cron.ts

- src/index.ts
Should fix the log4js workers not all printing to console.
[Found here](https://github.com/log4js-node/log4js-node/issues/265#issuecomment-544974438)
> fix: log4js logging

- .releaserc.json
Same setup as `sudosos-frontend`
> ci: remove semantic-release comments

- src/controller/invoice-controller.ts
> feat: Add query param to force invoice pdf

- src/controller/debtor-controller.ts
- src/controller/invoice-controller.ts
- src/controller/payout-request-controller.ts
- src/controller/seller-payout-controller.ts
- src/controller/user-controller.ts
- test/unit/controller/debtor-controller.ts
- test/unit/controller/user-controller.ts
Easier to distinguish in the FE if it was SudoSOS or the PDF-GENERATOR that failed.
> feat: return 502 for PDF generator errors

- src/index.ts
Requires that the `NAME` env variable is set.
#300 
> fix: add validation for NAME environment variable

- src/database/database.ts
- src/migrations/1726066600389-seller-payout-pdf.ts
Not sure how this got in, again, we do need a good refactor of how we migrate and stuff for testability.
> fix: mistake in seller payout pdf migration

- src/database/database.ts
- src/migrations/1726066600389-seller-payout-pdf.ts
> fix: mistake in seller payout pdf migration (#315)

- src/controller/seller-payout-controller.ts
> fix: missing security tag

- src/controller/user-controller.ts
> fix: swagger return array fix

- src/controller/seller-payout-controller.ts
- src/controller/user-controller.ts
> chore: update main with develop

- src/controller/request/dinero-request.ts
- src/controller/response/dinero-response.ts
- src/controller/stripe-controller.ts
- src/service/debtor-service.ts
- src/service/invoice-service.ts
- src/service/payout-request-service.ts
- src/service/seller-payout-service.ts
- src/service/stripe-service.ts
- src/service/transaction-service.ts
- src/service/transfer-service.ts
- src/service/write-off-service.ts
- test/unit/controller/stripe-controller.ts
- test/unit/service/debtor-service.ts
- test/unit/service/invoice-service.ts
- test/unit/service/seller-payout-service.ts
Makes creating Dinero objects easier, as the object types now completely overlap.
- Style _(Change that do not affect the functionality of the code)_
> style: dinero request and response objects now extend `DineroObject`

- src/controller/response/balance-response.ts
- src/service/balance-service.ts
- test/seed/ledger/fine-seeder.ts
- test/unit/controller/balance-controller.ts
- test/unit/service/balance-service.ts
Add two extra self-explanatory fields to `BalanceResponse`.
Fixes https://github.com/GEWIS/sudosos-backend/issues/352 and https://github.com/GEWIS/sudosos-backend/issues/346.
> feat: add nrFines and lastTransactionDate to `BalanceResponse`

- README.md
Looks cool right
- Documentation improvement
> docs: add uptime badge to README

- src/controller/balance-controller.ts
I was looking for a way to get all users with a fine, apparently this existed but it said in the API that it was for current user.
So, I fixed it for the future.
> fix: balance-controller-documentation

- .github/workflows/build.yml
V3 will be deprecated between November 30 and December 5. After this, usage of v3 will result in a workflow failure.
There are some [breaking changes in v4](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md), however, I do not think this workflow is impacted by those changes.
> ci: update artifact upload action

- src/controller/response/transaction-summary-response.ts
- src/controller/transaction-summary-controller.ts
- src/index.ts
- src/service/transaction-summary-service.ts
- test/unit/controller/transaction-summary-controller.ts
- test/unit/service/transaction-summary-service.ts
Hotfix for Feestcafé "De BAC" 2, to fetch how many contributions are made towards the fundraiser. Code is small and limited due to time constraints, but should cover the exact case I need.
> feat(summaries): add endpoint to fetch container's summary

- src/index.ts
- test/unit/controller/transaction-summary-controller.ts
I took a shortcut and it blew up in my face...
> hotfix(summaries): fix all endpoints returning 405

- src/controller/response/transaction-summary-response.ts
- src/controller/transaction-summary-controller.ts
- src/service/transaction-summary-service.ts
- test/seed/user-seeder.ts
- test/unit/controller/transaction-summary-controller.ts
- test/unit/service/transaction-summary-service.ts
I forgot that this was a thing... @JustSamuel thanks for the heads-up. Please notify me in advance when deploying this, because this PR will break the poster currently in deployment. This PR should however not be marked as a breaking change, because this functionality was already unstable/experimental/minimal to begin with.
> fix(summaries): users with extensive data processing disabled are now always excluded

- src/controller/user-controller.ts
> fix: mistake in nfcode swagger annotation

- init_scripts/start.sh
- src/cron.ts
- src/helpers/logging.ts
- src/index.ts
Since the new pms config the cron logging setup never changed, resulting in a lack of logs.
> fix: cron application not logging to console

- .github/workflows/build.yml
- .github/workflows/docker-build.yml
- .github/workflows/docker-push.yml
- .github/workflows/docs.yaml
- .github/workflows/release.yml
Now generally passes actionlint
> ci: bump action versions

- src/service/container-service.ts
> fix: contain delete propagated to wrong pos

- .github/workflows/build.yml
- src/controller/invoice-controller.ts
- src/database/database.ts
- src/service/container-service.ts
- src/service/invoice-service.ts
- test/root-hooks.ts
- test/setup.ts
- test/unit/service/invoice-service.ts
Small fixes, and an important container deleting bugfix.
> Update main from develop

- src/controller/banner-controller.ts
- src/controller/request/banner-request.ts
- src/controller/response/banner-response.ts
- src/entity/banner.ts
- src/entity/file/banner-image.ts
- src/service/banner-service.ts
> docs(banners): add `banner` docs

- src/controller/response/debtor-response.ts
- src/service/debtor-service.ts
Adds the amount of total fines of a fine handout event in the BaseFineHandoutEventResponse
Already made a PR, not sure if .amount is the preferred way.
#479 
> feat(debtor): add amount to BaseFineHandoutEventResponse

- Dockerfile
> fix: docker file errors

- package-lock.json
- test/unit/controller/transaction-controller.ts
- test/unit/service/transaction-service.ts
https://github.com/GEWIS/sudosos-backend/actions/runs/14170635537/job/39703931457
> chore: fix package-lock.json

- src/service/invoice-service.ts
`fromDate` and `tillDate` were ignored.
> fix: add date to invoice getOptions where clause

- .github/workflows/docker-push.yml
- Dockerfile
- package-lock.json
- package.json
- src/controller/balance-controller.ts
- src/controller/response/balance-response.ts
- src/service/balance-service.ts
- src/service/invoice-service.ts
- test/unit/controller/balance-controller.ts
- test/unit/controller/transaction-controller.ts
- test/unit/service/balance-service.ts
- test/unit/service/transaction-service.ts
Mostly deps, but also some small features and fixes.
-  Release
> Update main form develop

- .github/workflows/build.yml
Fixes the coverage reporting missing the "per line" change.
Closes #337
> Fix coverage report per line

- src/rbac/default-roles.ts
This way everybody can update their pin code
> fix(rbac): allow users to update their pinCode

- src/rbac/role-manager.ts
- src/service/sync/user/ldap-sync-service.ts
Add a bit more logging to check what is going on
> Add additional logging to ldap role sync

- src/controller/transaction-controller.ts
- src/service/transaction-service.ts
- test/unit/controller/transaction-controller.ts
Similar to `excludeById` but then for `fromId`. Can be used to see which transactions you have made for others (i.e. as BAC what did I just enter?)
> feat: add `excludeFromId` as filter option

- pm2.json
> fix: cron process cluster mode blocking websocket connections

- src/rbac/default-roles.ts
> fix: maintenance permissions of default-roles

- src/service/user-service.ts
Refactored the search query logic to improve clarity. Instead of manually handling multiple conditions for first name, nickname, and last name separately, we now use `CONCAT` to allow direct searches of full names.
However, this does mean that the e-mail address of a user now also becomes a part that is searchable. Kept limit to two for separate parts. Additionally, the parameters are structured more cleanly.
---
The used collation (`utf32_general_ci`) already ensures case-insensitive matching. However, as noted in my review in
https://github.com/GEWIS/sudosos-backend/pull/57#pullrequestreview-1607553958, I still believe using `utf32` is unnecessary at best and `utf8mb4` should be used instead (except that TypeORM does not directly allow usage of the `unicode_ci` variant over …
> feat: improved user search
