- src/controller/debtor-controller.ts
- src/entity/transactions/transaction.ts
- src/gewis/gewis.ts
- src/mailer/templates/user-got-fined.ts
- src/mailer/templates/user-will-get-fined.ts
- src/service/debtor-service.ts
- src/service/transaction-service.ts
- test/unit/controller/debtor-controller.ts
- test/unit/entity/transactions/transaction.ts
- test/unit/entity/transactions/transfer.ts
- test/unit/service/debtor-service.ts
Users will get an automatic email once they go into debt by making a transaction.
The treasurer can send notifications manually to people that they will get fined next time. This email is however only sent to people who are actually eligible for a fine at the time of sending.
> Add debt and fine email notification warnings

- src/service/user-service.ts
The database has its charset set to `utf32` and the collation to `utf32_general_ci`. Forcing the search queries to collate with `utf8_general_ci` breaks, as this is not supported. The `COLLATE` statement is not necessary.
Because GH-56 did not work as expected. This code has already been tested and verified to work.
> Remove collation from search queries

- Dockerfile
- init_scripts/start.sh
- package.json
- process.json
- src/cron.ts
- src/database/database.ts
- src/index.ts
Should improve performance of SudoSOS and stop the POS from "hanging". It is the same fix as was implemented in the SNiC CelerIT backend. However, because SudoSOS also has timed tasks to synchronize stuff, these had to be moved to a separate file. Otherwise, each worker would start the tasks at exactly the same time and thus the same work would be done four times, defeating the point of having workers.
The docker container starts correctly on my machine, but I have not yet tested whether SudoSOS actually works correctly, as I do not have a production environment setup on my machine. Therefore, I propose to test this on sudosos.test.gewis.nl.
> Change NodeJS runner to add more workers & improve performance

- src/service/stripe-service.ts
- src/subscriber/transfer-subscriber.ts
- test/unit/controller/transaction-controller.ts
TypeOrm failed to correctly save the stripe deposit status within the type orm transaction (because reasons?), Stating the id seemed to work.
> Hotfix for stripe transaction erroring on deposit update

- src/controller/balance-controller.ts
- src/controller/invoice-controller.ts
- src/entity/user/user.ts
- src/service/invoice-service.ts
- src/subscriber/transaction-subscriber.ts
- test/unit/subscribe/transaction-subscriber.ts
Filtering is flawed in a couple places, and should be up to the latest spec (as seen on GET /balances/all). This PR should fix that, along with some filtering issues where the parameter seems to be simply ignored.
Fixes #84.
TODO:
> Fix filtering and make it more consistent across the API and fix user debt notifications

- src/service/invoice-pdf-service.ts
Accidentally used the transfer amount, which ignores custom entries.
> bugfix: fixed total amount on invoice

- src/controller/stripe-controller.ts
- src/service/stripe-service.ts
- test/unit/service/stripe-service.ts
Introduces validation for the maximum amount a top-up can have; to verify that the user can only top-up their balance with €150 minus their current balance.
> feat: maximum top-up amount check

- test/unit/controller/stripe-controller.ts
Analysis shows that the `seedStripeDeposits` can/will create 3 valid Stripe deposits resulting in a balance of 117 euros. A top-up of another 39 euros will thus fail as this exceeds the 150 euro balance limit.
Instead of changing the seeding (which may inadvertantly affect other tests) we simply change the amount of the top-up to €19.50.
Fixes GH-180.
> fix: `StripeController` test with too high test balance

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Adds basic templates for issues and PR's.
based on sudosos-frontend
> ci: add issue templates for bug reports and feature requests

- src/controller/user-controller.ts
- src/service/transaction-service.ts
- test/unit/controller/user-controller.ts
Remove transactions created by the user from the transactions overview of the user (as well as the financial mutation)
Currently, financial mutations and transactions on `/user/{id}/transactions` and `/user/{id}/financialmutations` return also transactions that are created by the user. This PR removes that functionality. The idea is that all the financial mutation (transactions, transfers, and financialmutation) on the `/user/*` should only return transactions/transfers that mutate the user's balance. 
This is also tied into the frontend, where it would only make sense to display only transactions that influence the balance of the user together, serving the purpose of being able to see why you are €-15 when you topped up a week ago. Transactions that are created by the user should be …
> Remove createdBy transactions on the user related endpoints.

- src/controller/invoice-controller.ts
- test/unit/controller/invoice-controller.ts
- test/unit/service/balance-service.ts
Since the BACPM makes credit invoices for ORGAN users it seems reasonable to also allow defaults for those.
#193 
> Fix:issue 193 invoice allow defaults for  ORGANS

- package-lock.json
- package.json
- src/service/stripe-service.ts
- test/unit/service/stripe-service.ts
Update Stripe API version to `2024-06-20`, the latest version. I have not verified whether it works correctly on the frontend, because I did not get it fully running locally and was not bothered to spend hours trying to fix it. @JustSamuel could you maybe check? Or we just test it on SudoSOS Test.
Fixes https://github.com/GEWIS/sudosos-backend/issues/185.
> chore(deps): update Stripe API version

- src/controller/payout-request-controller.ts
- src/controller/request/payout-request-request.ts
- test/unit/controller/payout-request-controller.ts
- test/unit/service/payout-request-service.ts
Currently the BACPM is unable to create payout requests for other users, which is a bummer if those accounts are blocked and or deactivated. 
> Feature: create payout request for others

- src/controller/container-controller.ts
- src/controller/point-of-sale-controller.ts
- src/controller/product-controller.ts
- src/database/database.ts
- src/entity/container/container-revision.ts
- src/entity/container/container.ts
- src/entity/point-of-sale/point-of-sale.ts
- src/entity/product/product-revision.ts
- src/entity/product/product.ts
- src/migrations/1720608140757-soft-deletes.ts
- src/service/container-service.ts
- src/service/invoice-pdf-service.ts
- src/service/point-of-sale-service.ts
- src/service/product-service.ts
- src/service/transaction-service.ts
- test/helpers/balance.ts
- test/helpers/user-factory.ts
- test/seed.ts
- test/unit/controller/container-controller.ts
- test/unit/controller/point-of-sale-controller.ts
- test/unit/controller/product-controller.ts
- test/unit/controller/transaction-controller.ts
- test/unit/service/balance-service.ts
- test/unit/service/container-service.ts
- test/unit/service/point-of-sale-service.ts
- test/unit/service/product-service.ts
- test/unit/service/transaction-service.ts
Adds endpoints for deleting products, containers and points of sale.
The three aforementioned entities could not be deleted from the database, because that would invalidate the data, as transactions have a reference to their point of sale, container and product. To solve this, products, containers and points of sale are soft deleted under the hood. When they are soft deleted, they will never be returned in any endpoint except in the context of transactions. Soft deleted products, containers and points of sale can also not be used as correlated entities or within transactions.
When soft deleting, the entity corresponding entity is only marked as soft deleted. However, due to the aforementioned restrictions, it will never be shown again (even though a soft deleted product might still be …
> Feature: add deleting products, containers and points of sale

- .github/workflows/build.yml
> ci: warn instead of fail if base coverage is not found.

- package-lock.json
- package.json
- src/cron.ts
- src/gewis/service/cli-service.ts
- src/gewis/service/gewisdb-service.ts
- src/service/user-service.ts
- test/unit/gewis/gewisdb.ts
Since syncing the complete SudoSOS user list might be a bit much, I suggest a dry-run from cli to inspect the results.
> feat: add dry-run cli option for GEWISDB sync

- src/gewis/service/gewisdb-service.ts
Since this uses `AppDataSource` you cannot use other services (yet), as they use the default connection.
> fix: return before balance to prevent AppDataSource based errors

- src/controller/request/transfer-request.ts
- src/controller/response/transfer-response.ts
- src/database/database.ts
- src/entity/transactions/transfer.ts
- src/migrations/1721916495084-transfers-vat.ts
- src/service/balance-service.ts
- src/service/debtor-service.ts
- src/service/invoice-service.ts
- src/service/transfer-service.ts
- src/service/voucher-group-service.ts
- src/subscriber/transfer-subscriber.ts
- test/helpers/balance.ts
- test/helpers/transaction-helpers.ts
- test/seed.ts
- test/unit/service/debtor-service.ts
- test/unit/service/invoice-pdf-service.ts
- test/unit/service/invoice-service.ts
- test/unit/service/stripe-service.ts
- test/unit/service/transfer-service.ts
- test/unit/service/voucher-group-service.ts
Since `WriteOffs` and `Inactivity Fees` have a VAT percentage but are not products, we have a need for adding VAT groups to transfers. This PR implements the bases of this. 
> feat: add vat to transfers

- src/controller/point-of-sale-controller.ts
- src/controller/request/point-of-sale-request.ts
- src/controller/request/validators/general-validators.ts
- src/controller/request/validators/point-of-sale-request-spec.ts
- src/controller/request/validators/validation-errors.ts
- src/controller/response/point-of-sale-response.ts
- src/controller/response/transaction-response.ts
- src/database/database.ts
- src/entity/point-of-sale/point-of-sale.ts
- src/helpers/revision-to-response.ts
- src/migrations/1721835613950-pos-cashiers.ts
- src/migrations/1722022351000-pos-cashiers.ts
- src/service/point-of-sale-service.ts
- src/service/user-service.ts
- test/unit/controller/point-of-sale-controller.ts
- test/unit/service/point-of-sale-service.ts
Adds a many-to-many relation between POSs and roles, allowing to associate groups of users with POSs. There already exist a way to do this, namely via ownership using the `MemberAuthenticator`. However, this is ownership, so all users are (in theory) able to make changes to the POS. 
This PR allows a second group of users to be linked to a POS, namely "cashiers". In practice, this will be the BAC feuten, so they can also create transactions in their own name during borrels. Right now, they do this in the name of a BAC member, which is confusing. To keep changes to SudoPOS minimal, there is a new endpoint that returns all users associated with a POS, seperated by their relation with the POS.
> feat: POS cashier roles

- src/database/database.ts
- src/entity/server-setting.ts
- src/index.ts
- src/migrations/1722083254200-server-settings.ts
- src/server-settings/server-settings-store.ts
- src/server-settings/setting-defaults.ts
- test/unit/server-settings/server-settings-store.ts
Helper class to store system global settings in the database (instead of an environment variable). The store is synchronous in fetching settings, but this requires settings to be cached locally. Even though you can dynamically change these settings by using the `setSetting` method, the setting will then only change in that particular worker until SudoSOS is rebooted.
Or we can make the `getSetting` also asynchronous, which would solve this issue. What do you prefer?
Implements https://github.com/GEWIS/sudosos-backend/issues/226;
> feat: add server settings to store global settings in database

- src/controller/payout-request-controller.ts
- src/controller/response/payout-request-response.ts
- src/service/payout-request-service.ts
- test/unit/controller/payout-request-controller.ts
- test/unit/service/payout-request-service.ts
Refactors the `payout-request-service` and fixes some bugs
@Yoronex in the invoice setup we use an extra column, here we use a subquery to filter on current states. What is the better setup? Since the invoice needed a migration I suggest not to change it.
> refactor(payoutrequests): move to `getOptions` method

- src/controller/product-category-controller.ts
- src/controller/request/product-category-request.ts
- src/controller/response/product-category-response.ts
- src/database/database.ts
- src/entity/product/product-category.ts
- src/migrations/1722517212441-nested-product-categories.ts
- src/service/product-category-service.ts
- test/seed.ts
- test/unit/controller/product-category-controller.ts
- test/unit/service/product-category-service.ts
Upgrades product categories from simple, standalone entities to tree entities. This means that each category can now optionally have a parent category, which allows us to further distinguish different types of products. Examples are Wines (white, red, rose) and Beers (pils, tripel, blond, dubbel, etc). The `GET /productcategories` endpoint now has optional query filters to only get root categories (which are the tabs in the POS) or to only get leaf categories. However, for the POS to understand in which root category a subcategory belongs, its best for the POS to simply request all categories from the backend and then create a local mapping of categories to their root category.
Other uses are mostly statistics-related, so we can for example better understand what types of products are …
> feat: nested product categories

- src/service/stripe-service.ts
- test/unit/service/stripe-service.ts
It seems I made a stupid mistake while working on the `stripe-service` that remained undiscovered due to a faulty test. This is now fixed. However, the Stripe events were indeed all handled correctly, so there are two options to fix these issues:
1. For all these topups, we remove the "success" state and send all the webhook events again. We therefore act as if we have never processed these topups up to now (my preference).
2. We manually create transfers for all "success" deposits that have no transfers attached to them.
Actual fix for https://github.com/GEWIS/sudosos-backend/pull/281.
> fix: Stripe webhook success event never creating a transfer

- src/controller/response/report-response.ts
- src/controller/response/vat-group-response.ts
- src/controller/user-controller.ts
- src/entity/report/report.ts
- src/helpers/validators.ts
- src/service/container-service.ts
- src/service/point-of-sale-service.ts
- src/service/product-service.ts
- src/service/report-service.ts
- src/service/sales-report-service.ts
- src/service/vat-group-service.ts
- test/helpers/transaction-factory.ts
- test/unit/controller/invoice-controller.ts
- test/unit/controller/user-controller.ts
- test/unit/service/invoice-service.ts
- test/unit/service/report-service.ts
- test/unit/service/transaction-service.ts
Implements a new Sales Reporting function, as described in https://github.com/GEWIS/sudosos-backend/issues/260 and marked as a TODO here https://github.com/GEWIS/sudosos-backend/pull/259.
This is *SO* much faster. It is not even funny, aggregating the whole database is instant. This is because the new service writes queries instead of fetching data and computing the statistics itself. This is how it should always have but the previous reporting function got some scope creep to try and make it more versatile.
This leaves the old reporting untouched, for backwards compatability.
> feat: add sales-report-service

- .env-example
- src/authentication/token-handler.ts
- src/controller/stripe-webhook-controller.ts
- src/entity/user/user.ts
- src/service/stripe-service.ts
- test/unit/controller/stripe-controller.ts
- test/unit/controller/stripe-webhook-controller.ts
Adds a description and metadata to Stripe PaymentIntents. The metadata contains a `service` key, which includes the new `NAME` environment variable. This variable should contain the name of the service, for example `sudosos-prod` or `sudosos-test`. When receiving Stripe webhook events, SudoSOS checks whether this service name matches. If so, it will actually process the webhook event. **If not, it will still return a 204 to Stripe, but not process the event any further.** It is therefore important that we add these environment variables when deploying.
Fixes https://github.com/GEWIS/sudosos-backend/issues/288.
> feat: add description and metadata to Stripe PaymentIntents

- src/authentication/json-web-token.ts
- src/controller/authentication-controller.ts
- src/controller/authentication-secure-controller.ts
- src/controller/response/server-status-response.ts
- src/controller/root-controller.ts
- src/controller/server-settings-controller.ts
- src/entity/server-setting.ts
- src/gewis/controller/gewis-authentication-controller.ts
- src/index.ts
- src/middleware/restriction-middleware.ts
- src/rbac/default-roles.ts
- src/server-settings/server-settings-store.ts
- src/server-settings/setting-defaults.ts
- src/service/authentication-service.ts
- src/service/write-off-service.ts
- test/unit/controller/authentication-controller.ts
- test/unit/controller/root-controller.ts
- test/unit/controller/server-settings-controller.ts
- test/unit/middleware/restriction-middleware.ts
- test/unit/server-settings/server-settings-store.ts
Adds maintenance mode to the `restriction-middleware`. The following rules apply:
- Maintenance mode is added as a server setting
- All endpoints (except LDAP login, local login and `/ping`) will return a 503 once maintenance mode is enabled.
- All users that have the permission `Maintenance override` can always access all endpoints, even during maintenance.
- Maintenance mode can be enabled/disabled using a new endpoint.
Fixes https://github.com/GEWIS/sudosos-backend/issues/280.
> feat: add maintenance mode to restrict access to SudoSOS during upgrades

- src/migrations/1725196803203-user-type-enums.ts
MariaDB failed on migration because of changing the column causing the 1 to become a string 1
> fix: mistake in user-type-enums migration

- src/controller/debtor-controller.ts
Did a little oopsie and forgot to change this parameter type.
- Breaking change _(fix or feature that would cause existing functionality to change)_
> fix: wrong query param type for `userType` in Swagger

- src/service/user-service.ts
- test/unit/controller/user-controller.ts
`GET /users/` returns users ordered by `id` descending.
#273 
> fix: add ordering by user ID in descending order

- test/root-hooks.ts
- test/setup.ts
- test/unit/controller/debtor-controller.ts
- test/unit/gewis/gewisdb.ts
- test/unit/mailer/mailer.ts
- test/unit/service/debtor-service.ts
- test/unit/service/event-service.ts
- test/unit/subscribe/transaction-subscriber.ts
Adds mocha root hooks to the test suite. Right now, the only root hook is one to stub `nodemailer.createTransport`, which prevents all the "SMTP connection refused" error messages during the tests. But more importantly, if a SMTP server is configured in the environment variables, no connection shall actually be made.
The root hooks are implemented in such a way that more stubs can be added in the future.
When you want to use your own stub instead of a root stub, you have to manually restore these stubs **before running each test case**. Examples can be found in the existing test cases. Due to limitations of Mocha, it is not possible to run these hooks before every suite (either once before all tests, or once for each test case).
- Style _(Change that do not affect the functionality of the …
> chore(tests): globally mock mailer SMTP connection

- src/service/debtor-service.ts
- test/unit/service/debtor-service.ts
Fine reports were always across the full existence of SudoSOS.
> fix: dates not being used in fine report

- src/controller/request/validators/invoice-request-spec.ts
- src/controller/request/validators/validation-errors.ts
- test/seed/ledger/invoice-seeder.ts
- test/unit/controller/invoice-controller.ts
`DELETED` Was already nicely implemented, but not for `PAID`.
#107 
> fix: disallow editing invoices that are deleted or paid

- src/database/database.ts
- src/entity/authenticator/ldap-authenticator.ts
- src/helpers/ad.ts
- src/migrations/1726689003147-ldap-objectguid.ts
- src/service/ad-service.ts
- src/service/authentication-service.ts
- test/unit/controller/authentication-controller.ts
- test/unit/gewis/controller/gewis-authentication-controller.ts
- test/unit/gewis/gewis.ts
- test/unit/service/ad-service.ts
- test/unit/service/authentication-service.ts
Mixing little endian and big endian should be considered a warcrime. 
https://joelitechlife.ca/2021/04/05/get-objectguid-of-microsoft-active-directory-using-ldapsearch/
> fix: handle ObjectGUID as Buffer correctly

- src/migrations/1726689003147-ldap-objectguid.ts
Guess this went wrong somewhere during the testing on sudosos-test db. 
Verified the migration locally using an old recovery.
> fix: missing save in migration

- src/controller/debtor-controller.ts
- src/controller/request/debtor-request.ts
- src/controller/user-controller.ts
- src/service/debtor-service.ts
- test/unit/controller/user-controller.ts
- test/unit/service/debtor-service.ts
- test/unit/subscribe/transfer-subscriber.ts
After merging the PR, a `UserFineGroup`'s can be partially waived, instead of only all of them. The following decision decisions/restrictions are made:
1. The workflow of waiving all user's fines has not changed. When all fines of a user are waived, the user will no longer have any outstanding fines.
2. When waiving fines partially, the user will no longer have any outstanding fines if they go out of debt after the waiving.
3. When a user gets its fines partially waived and remains in debt, the user will still have outstanding fines. If they get a new fine, this new fine will be added to the total outstanding amount (the same `UserFineGroup`).
4. When a user's fines of the same `UserFineGroup` are waived _again_, this new amount to waive will override the old amount. In other words, the …
> feat: partially waive user's fines

- src/controller/event-controller.ts
- src/controller/event-shift-controller.ts
- src/controller/request/event-request.ts
- src/controller/response/event-response.ts
- src/entity/event/event-shift-answer.ts
- src/entity/event/event-shift.ts
- src/entity/event/event.ts
- src/mailer/messages/forgot-event-planning.ts
- src/service/event-service.ts
- test/seed/event-seeder.ts
I have marked all event-related code as deprecated to the best of my abilities. I also added a comment in the deprecation that these deprecations can be removed from November 1st 2026 onwards (two years from now). If we have never moved this code to another project before that time, I assume it will never happen.
Fixes https://github.com/GEWIS/sudosos-backend/issues/347.
- Style _(Change that do not affect the functionality of the code)_
> chore: deprecate all Event-related code

- package.json
It is a known issue that vitepress needs a lot of memory, and my initial guess of 8 was not enough it looks like:
https://github.com/GEWIS/sudosos-backend/actions/runs/11384654463/job/31672832304?pr=338
> chore: increase memory for docs:build

- src/controller/balance-controller.ts
Another one, the getAllBalance returns a BalanceResponse in the controller. This should be a PaginatedBalanceResponse
> fix: balance-controller-documentation

- package.json
Because of this:
```
> sudosos-back-end@0.1.0 watch
> nodemon --watch "src/**" --ext "ts,json" --exec "ts-node src/index.ts
sh: 1: Syntax error: Unterminated quoted string
```
> ci: fix `cron` and `watch` command missing quote

- src/controller/user-controller.ts
- test/unit/controller/user-controller.ts
Adds an endpoint to the user-controller to lookup a user by nfc code. Intented implementation will be for the POS to allow charging a user by simply scanning their nfc code.
#422 
> feat(users): add endpoint to lookup user from nfc code

- src/service/product-service.ts
This filtering, which is present in the update product and container logic, was missing in the delete function. This caused deletions to be propagated to "burried" containers, resulting in immense amount of useless updates. 
> fix: product deletion propagation to unneeded containers

- .github/workflows/build.yml
- src/database/database.ts
- test/root-hooks.ts
- test/setup.ts
Hopefully, this also speeds up the tests.
> Remove deprecated typeorm function and fix hanging test suite.

- src/controller/invoice-controller.ts
- src/service/invoice-service.ts
- test/unit/service/invoice-service.ts
Also changes the name to `getEligibleTransactions` since that describes the function better.
The function was used to ensure that a time range did not contain invoiced transaction, however since the big rework you are required to send all transaction ids anyhow, so this makes much more sense atm.
#435 
> Fix  `getTransactionsForInvoice` returning invoiced transactions

- src/service/invoice-service.ts
- src/service/transaction-service.ts
Soft-deleted relations are not handled super nicely by TypeORM. This caused deleted products to fail when being retrieved, even if it was for historical purpose (retrieving old transactions, for example.)
Closes #460 
> Deleting products or containers causes queries to fail

- src/service/transaction-service.ts
Currently, balance cache is cleared when a transaction is created/updated/ deleted for a user. However, balance cache should not be invalidated when creating a transaction.
Creating a transaction is an action forward; new balance is just the sum of balance cache + all new transactions for that user. Thus, no need to remove it. Invalidating it is also bad for performance, as balance has to be calculated on the fly until next balance cache calculation (cronjob).
This removes balance cache invalidation for transaction creations.
---
Here confirmation of the old behaviour:
After creating a transaction:
GH-466
> fix: balance cache invalidation on transaction creation

- Dockerfile
During the Ubuntu Summit I was lead down a rabbit hole of inspecting docker images. I noticed that the sudosos-backend could use some improvement.
I noticed that the npm ci still installed dev dependencies in the runtime container, so that was fixed. Furthermore when installing npm packages, it also adds to the cache. Meaning it used to have 2x the node_modules installed in the image. By installing in the build container and copying to the runtime container, we circumvent this issue.
The build from 6 days ago is the current develop docker image, the docker image from 9 minutes ago is this the one that has the improvement. 
Here you can see the cache being added which is about the same size as the node_modules themself:
My improved image is currently running on develop (28-10-2024 10:53), …
> fix(docker): reduce size of image by about half

- .github/workflows/docker-push.yml
Seems to work behind the WAF, and pushing to GitHub is "extra". Not sure yet what to do with the images we have on github, I suggest removing them so there is no mistake which one is leading.
> Remove pushing of docker image to GitHub

- src/controller/balance-controller.ts
- src/controller/response/balance-response.ts
- src/service/balance-service.ts
- test/unit/controller/balance-controller.ts
- test/unit/service/balance-service.ts
Added a balance service function to get a added up value of positive and negative balances. you can also decide to do this for all users or only for users that can top up (member and local)
This should decrease the time it takes to calculate this as in the frontend this now takes +- 14 seconds.
- Breaking change _(fix or feature that would cause existing functionality to change)_
> feat: total-balances-sudosos

- src/controller/balance-controller.ts
- src/service/balance-service.ts
- test/unit/service/balance-service.ts
Adds query param to `getBalances` to fetch inactive users' balances.
> feat: add query param to fetch inactive user balances

- src/service/websocket-service.ts
- test/unit/service/websocket-service.ts
Send the current maintenance status when a client connects to the `system` room on the WS.
This is so that if the POS gets refreshed when it is in maintenance, the overlay gets shown again.
> feature: send maintenance status on ws connection

- src/controller/write-off-controller.ts
- src/service/write-off-service.ts
- test/unit/controller/write-off-controller.ts
Simple feature to add createdAt as query params for `GET /write-offs`. Useful with the idea of working on a financial overview later (e.g., get all write-offs in a fiscal year).
> feat: add `createdAt` filter params for write-offs

- src/entity/user/user.ts
- test/unit/service/user-service.ts
The changes in this PR remove the `INVOICE` account type from the `LocaluserTypes` list.
This makes it so that no reset password mail is sent out the the associated email.
https://github.com/GEWIS/sudosos-backend/issues/549
> fix: remove invoice from local user types
